[project]
name = "pendulum-examples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "myrtle",
]

[tool.uv.sources]
myrtle = { path = "../myrtle", editable = true }
